version: '3.8'

services:
  app:
    build:
      context: .
      target: dev
    command: npx nodemon src/index.js --watch src
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
